### ISSUE TITLE
As a Developer, I need to have a way to encode/decode Mina messages in Rust so I can implement an independent Mina peer

### ISSUE THREAD

**Issue by akoptelov** [name-placeholder/mina-p2p-messages-rs#1]
### Definition of "done"

A Rust library developed that contains type definitions for all Mina gossip and RPC messages with possibility to encode/decode using `bin prot` schema.

- [x] #5
- [x] #3 
- [x] #12
- [x] #13
- [x] #7
- [x] Unit tests
- [x] #6
- [x] #8
- [x] #18
- [x] name-placeholder/bin-prot-rs#2
- [x] #19 
- [x] name-placeholder/bin-prot-rs#1

**Comment by akoptelov** [comment]
Implementing RPC decoding.

**Comment by akoptelov** [comment]
RPC `get_epoch_ledger` is implemented. Working towards other RPCs and a kind of a registry for defined method.

**Comment by akoptelov** [comment]
The list of V1 RPCs:

- [ ] `get_some_initial_peers`
- [ ] `get_staged_ledger_aux_and_pending_coinbases_at_hash`
- [ ] `answer_sync_ledger_query`
- [ ] `get_transition_chain`
- [ ] `get_transition_chain_proof`
- [ ] `Get_transition_knowledge`
- [ ] `get_ancestry`
- [ ] `ban_notify`
- [ ] `get_best_tip`
- [ ] `get_node_status`
- [ ] `get_epoch_ledger`

**Comment by akoptelov** [comment]
RPC doc: https://github.com/name-placeholder/mina-wiki/blob/master/p2p/mina-rpc.md

**Comment by akoptelov** [comment]
V2 Gossip messages are done. Now working on RPCs for V2

**Comment by akoptelov** [comment]
Adding bencmarking, for both native and wasm32.

**Comment by akoptelov** [comment]
Implementing memory consumption benchmarks.

**Comment by akoptelov** [comment]
**_Performance test_**
Decoding of input messages, incoming RPCs captured during catch-up process in berkeleynet (~80M), x10 times.

Native:
```
mean: 0.26560021159999997, stdev: 0.0003018581737673776 
```

Wasm32 (Firefox):
```
    mean: 0.457054, stdev: 0.030821437443052
```

Wasm32 (Chrome):
```
    mean: 0.4464769999, stdev: 0.055822759584718405
```

Wasm32 (Node):
```
mean: 0.4218, stdev: 0.011541959999999999
```

The summary is that there is a slight slow down when running as Wasm32, but it is less than x2.

**Comment by akoptelov** [comment]
### Memory Consumption Test

Decoding of input messages, incoming RPCs captured during catch-up process in berkeleynet (~80M).

Native:
```
Ratio: 1.5793496061764019
Encoded size (N): 64115
Currently allocated (B): 0
Maximum allocated (B): 101260
Total amount of claimed memory (B): 101260
Total number of allocations: (N): 2376
Reallocations (N): 0
```

Wasm32 (Firefox):
```
Decoded bytes: 89779897
Ratio: 1.3257730848142988
Total Allocated (Bytes): 208338833
Currently Allocated (Bytes): 1024
Allocation Peak (Bytes): 119027771
Number of reallocations (N): 24
```

Still in-memory representation is 1.3-1.5 times bigger than encoded size. That is mostly because of enums with variants of different size -- all variants (even empty) require amount of memory suitable for the biggest variant.

**Comment by akoptelov** [comment]
BTW, before [this fix](https://github.com/name-placeholder/mina-p2p-messages-rs/commit/543dd90776b3e274ede2bd8f5b0ae8cba002eb5e) memory consumption ratio was ~8 (runtime representation was >8 times bigger than encoded size), and wasm32 tests were 50% slower.

**Comment by tizoc** [comment]
@akoptelov how did that change help? unless there is something I am missing, that code still allocates the same memory as before, plus space for the pointer to the bytes (which were inlined before), right?

**Comment by akoptelov** [comment]
@tizoc For simplicity, imagine this:
```rust
struct BigInt([u8;32]);

enum Option {
    None,
    Some(BigInt),
}
```
Each instance of the `Option` will be 32 bytes, while in encoded form `Empty` will be only 1 byte. So for this case we will have x32 increment. Now, if it would be `struct BigInt(Box<[u8;32]>);`, the `Option` will be only 8 bytes long, so it will be 8x increment for the `Option::None` decoding.

**Comment by tizoc** [comment]
@akoptelov ahh I see. Thanks.

**Comment by akoptelov** [comment]
V2 wire types are generated without parameters now.
Working on boxing enum variants if needed.

**Comment by akoptelov** [comment]
Heap allocations while decoding a GetStagedLedgerAuxAndPendingCoinbasesAtHashV2 RPC response.

Before boxing alts:
```
Ratio: 10.53691387685571
Encoded size (N): 19003707
Currently allocated (B): 199575280
Maximum allocated (B): 199575280
Total amount of claimed memory (B): 200240424
Total number of allocations: (N): 831141
Reallocations (N): 2897
```

With boxed alts:
```
Ratio: 2.063837071367181
Encoded size (N): 19003707
Currently allocated (B): 38649787
Maximum allocated (B): 38649787
Total amount of claimed memory (B): 39220555
Total number of allocations: (N): 840462
Reallocations (N): 2895
```
In a nutshell, the peaked (maximal allocated) size went from almost 200M down to 39M, what is only 2x times more than encoded size.

With preallocated vectors in `binprot-rs`:
```
Ratio: 1.8691436886497987
Encoded size (N): 19003707
Currently allocated (B): 35513747
Maximum allocated (B): 35513747
Total amount of claimed memory (B): 35520659
Total number of allocations: (N): 837591
Reallocations (N): 24
```

**Comment by akoptelov** [comment]
Moved out security/safety items, they can be tracked elsewhere.

**Comment by akoptelov** [comment]
The fully functional library for Mina types is developed.
